### ISSUE TITLE
Clear internal DB?

### ISSUE THREAD

**Issue by jpmens** [owntracks/OwnTracksCTRL#14]
When a user first launches CTRL and gets data, and that data is incorrect b/c, say, incorrect publish topics configured on Greenwich, etc. the only way to currently "clear" the internal database is to switch user.

What do we do with people who don't have another username? I can swipe individual entries to delete them, but they return magically even though they've been cleared broker-side by publishing null payloads.

**Comment by ckrey** [comment]
Change user name: E.g. if user name is 'myuser' change it to 'myuse' and back to 'myuser'.

**Comment by ckrey** [comment]
Deleting entries in CTRL does not clear entries broker-side.

**Comment by jpmens** [comment]
Of course not; I had cleared broker-side before doing so in CTRL.

**Comment by ckrey** [comment]
So, to clear internal database:
a) delete and reinstall or
b) Change user name: E.g. if user name is 'myuser' change it to 'myuse' and back to 'myuser'.
