### ISSUE TITLE
Small typo in popup

### ISSUE THREAD

**Issue by jpmens** [owntracks/OwnTracksCTRL#16]
Should be singular: `device`

![image](https://cloud.githubusercontent.com/assets/60706/7550494/1d682b4e-f665-11e4-9d2f-c2786f474a99.jpg)

**Comment by ckrey** [comment]
Fixed:
![bildschirmfoto 2015-05-09 um 17 14 12](https://cloud.githubusercontent.com/assets/4027289/7550773/f142063e-f66e-11e4-9007-e0c10a1c0b55.png)
